### ISSUE TITLE
Can anyone help me with high memory consumption on Heroku platform?

### ISSUE THREAD

**Issue by ChameleonTartu** [heroku/heroku-buildpack-jvm-common#206] opened 2021-03-17 16:34 UTC
Hi,

I time-to-time building demo and production apps and deploying on Heroku. A few months ago, I bumped with this [issue](https://stackoverflow.com/questions/65480473/how-to-debug-unexpectedly-high-memory-use-with-docker-in-heroku).

I used Liberica JDK, which proved to be good in local dev env and production. Can you possibly help me out or point to the right repo/channel? I will highly appreciate any help on this.

Note: I used Java 11 and Kotlin with Jackson for object mapping. I tested this setup with Docker locally, and it wasn't supposed to bump any limits on the Heroku platform.

**Comment by rafaeldelboni** [comment] 2021-07-27 10:47
Having the same issue, in my machine it stays bellow 350 and in Heroku is going to pass the 512 ins a few hours.

The strangest part is that I can reproduce this locally and my heap+non heap is ~350mb and my RSS memory is ~506mb

Did you solved this issue @ChameleonTartu ?

**Comment by Malax** [comment] 2021-07-27 14:54
Hello @ChameleonTartu and @rafaeldelboni!

Sorry for the long delay before you got an answer. First off, let me say that the repository here is in no way contributing to your Docker container on Heroku. As per our [support policy](https://www.heroku.com/policy/support), we cannot help with debugging your application. However, here are my thoughts:

@ChameleonTartu Using Liberica is fine, I don't think this is where your problem is. In your linked StackOverflow questions, I can see that you're not explicitly passing any JVM options in. Are you sure you limit the maximum heap to a value that matches the dyno type you're using? 

@rafaeldelboni please note that Heap+NonHeap reported by the JVM is not all of RSS. The operating system inside the container requires memory as well. That might explain the difference in memory consumption you see.

I will close this as we cannot provide application debugging support and the issue is not related to the code in this repository.

**Closed by Malax** 2021-07-27 14:54 UTC

**Comment by ChameleonTartu** [comment] 2021-08-02 12:05
@rafaeldelboni I didn't solve it before. I am checking Malax's answer as I completely missed flags for limiting my heap. 🤦
