### ISSUE TITLE
Defaults to JDK1.8 when 14 is specified

### ISSUE THREAD

**Issue by jfullam** [heroku/heroku-buildpack-jvm-common#151] opened 2020-06-07 14:24 UTC
When specifying java.runtime.version=14 inside system.properties, the default JDK is used (1.8).  This could be because of the _get_jdk_url_with_default() function in bin/java does not account for a jdkVersion value of 14.

**Comment by jkutner** [comment] 2020-06-08 13:39
@jfullam the `_get_jdk_url_with_default()` func only exists to support a legacy behavior that uses env vars to set the Java version. The "14" in `system.properties` is handled in [`lib/jvm.sh`](https://github.com/heroku/heroku-buildpack-jvm-common/blob/master/lib/jvm.sh)

Can you double check that your `system.properties` is checked into Git, and on the `master` branch? thanks

**Comment by Malax** [comment] 2020-06-15 11:55
Hey @jfullam, have you been able to confirm your `system.properties` is correct and you still see the issue? Thanks!

**Comment by jfullam** [comment] 2020-06-15 16:24
Hi.  Yes, systems.properties is indeed checked in and jdk is set to 14 when
seeing this issue.

**Comment by Malax** [comment] 2020-06-17 08:52
I wasn't able to reproduce this, can you elaborate how you're using the buildpack? Are you using `heroku/jvm`, `heroku/java` or something that is using `heroku-buildpack-jvm-common`? Can you post the contents of your `system.properties` file?

**Comment by Malax** [comment] 2020-08-17 12:50
Closing due to inactivity, feel free to re-open.

**Closed by Malax** 2020-08-17 12:50 UTC
